// Generated by CoffeeScript 1.2.1-pre
(function() {
  var $, Browser, IIMJobs, X, ev, events, _;

  _ = require('underscore');

  $ = require('jquery');

  Browser = require('zombie');

  events = require('events');

  ev = new events.EventEmitter();

  console.log(ev);

  IIMJobs = (function() {

    IIMJobs.name = 'IIMJobs';

    _.extend(IIMJobs.prototype, new events.EventEmitter);

    function IIMJobs() {
      this.initialize.apply(this, arguments);
    }

    IIMJobs.prototype.initialize = function(options) {
      return this.emit('hello');
    };

    return IIMJobs;

  })();

  X = new IIMJobs();

  X.on('hello', function() {
    return console.log("here");
  });

}).call(this);
